myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path('about', views.about, name='about'),
    path('products', views.products, name='products'),
    path('products/<prod_id>',views.productdetail,name='productdetail'),
    path('placeorder', views.place_order, name='placeorder'),
    path('login',views.llogin,name='login'),
    path('user_login',views.user_login,name='userlogin'),
    path('myorders',views.myorders,name='myorders'),
    path('logout',views.user_logout,name='userlogout'),
    path('register',views.register,name='userRegister'),
    path('user_register',views.user_register,name='userregister'),
    path('<cat_no>',views.detail,name='detail'),

    ]

mysiteS19/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings



from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
      path(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=20, null=False, blank=True)

    def __str__(self):
        return self.name + ", " + self.warehouse


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100)
    available = models.BooleanField(default=True)
    description = models.TextField(max_length=100, null=True, blank=True)
    interested = models.PositiveIntegerField(default=0) #Added Positive Integer Field

    def __str__(self):
        return self.name

    def refill(self):
        st = self.stock + 100  # adds 100 to the current value of stock
        t = Product.objects.get(name=self.name)
        t.stock = st
        t.save()


class Client(User):
    PROVINCE_CHOICES = [
        ('AB', 'Alberta'),
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'), ]
    company = models.CharField(max_length=50, null=False, blank=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default='windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)

    def __str__(self):
        return self.first_name


class Order(models.Model):
    VALID_CHOICES = [
        (0, 'Order Cancelled'),
        (1, 'Order Placed'),
        (2, 'Order Shipped'),
        (3, 'Order Delivered')
    ]
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField(default=1)
    order_status = models.IntegerField(choices=VALID_CHOICES, default=1)
    status_date = models.DateField(default=timezone.now)

    def __str__(self):
        cost = self.product.price * self.num_units
        return 'Order# ' + str(self.id) + ': For ' + ' ' + self.product.name + " (#) by " + str(self.client) + ' and total amount is ' + str(cost)

    # def __str__(self):

    # return str(cost);

myapp/forms.py
from django import forms
from myapp.models import Order

#Created a class OrderForm with necessary widgets and labels
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['client', 'product','num_units']
        widgets = {'client': forms.RadioSelect(),}
        labels = {'num_units': u'Quantity', 'client': u'ClientName' }

#Created a class InterestForm with required fields and radioselect Button
class InterestForm(forms.Form):
    interested = forms.TypedChoiceField(widget=forms.RadioSelect, coerce=int, choices =((1, "Yes"), (0, "No")))
    quantity = forms.IntegerField(initial=1, min_value=1)
    comments = forms.CharField(widget=forms.Textarea, label='Additional Comments', required=False)

myapp/views.py
from django.shortcuts import render,redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponse
from .models import Category, Product, Client, Order
from .forms import OrderForm,InterestForm
from django.shortcuts import render
from django.utils import timezone
import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
lastlogin = 'Your last login was more than one hour ago'


def index(request):
        cat_list = Category.objects.all().order_by('id')[:10]
        if request.session.has_key('username'):
            lastlogin = request.session['last_login']
        else:
            lastlogin=''
        return render(request, 'myapp/index.html', {'cat_list': cat_list,'last_login':lastlogin})

def about(request):
        cookievalue = request.COOKIES.get('about_visits','default')
        if(cookievalue=='default'):
            response = render(request, 'myapp/about.html',{'about_visits':'1'})
            response.set_cookie('about_visits',1, 5*60)
            return response
        else:
            cookievalue=int(cookievalue)+1
            response = render(request, 'myapp/about.html', {'about_visits': cookievalue})
            response.set_cookie('about_visits', cookievalue)
            return response

def detail(request,cat_no):
        cat_list = Category.objects.filter(id=cat_no)
        product_list = Product.objects.filter(category__id=cat_no)
        return render(request, 'myapp/detail.html', {'cat_list': cat_list,'product_list':product_list})

def products(request):
        prodlist = Product.objects.all().order_by('id')[:10]
        return render(request, 'myapp/products.html', {'prodlist': prodlist})

def place_order(request):
    if request.session.has_key('username'):
        msg = ''
        prodlist = Product.objects.all()
        if request.method == 'POST':
            form = OrderForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                if order.num_units <= order.product.stock:
                    order.save()
                    p = Product.objects.get(name=order.product.name)
                    p.stock = order.product.stock - order.num_units
                    p.save()
                    msg = 'Your order has been placed successfully.'
                else:
                    msg = 'We do not have sufficient stock to fill your order.'
                return render(request, 'myapp/orderresponse.html', {'msg': msg})
        else:
            form = OrderForm()
            return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prodlist': prodlist})
    else:
        return redirect('/myapp/login')

def productdetail(request, prod_id):
        proddetail = Product.objects.get(id=prod_id)
        if request.method == 'POST':
            form = InterestForm(request.POST)
            if form.is_valid():
                if form.cleaned_data['interested'] == 1:
                    proddetail.interested=proddetail.interested+form.cleaned_data['interested']
                    proddetail.save()
            return redirect('/myapp/')
        else:
            form = InterestForm()
            return render(request, 'myapp/productdetail.html', {'form': form, 'proddetail': proddetail})

def llogin(request):
    if request.session.has_key('username'):
        return redirect('../myapp/')
    else:
        return render(request, 'myapp/login.html')

def user_login(request):
    if request.method == 'POST':
         username = request.POST['username']
         password = request.POST['password']
         user = authenticate(username=username, password=password)
         if user:
             if user.is_active:
                 login(request,user)
                 now = datetime.datetime.now()
                 lastlogin = now.strftime("%m/%d/%Y, %H:%M:%S")
                 request.session['username']=username
                 if not request.session.has_key('last_login'):
                     lastlogin = 'Your last login was more than one hour ago'
                     request.session['last_login'] = lastlogin
                     print(lastlogin)
                     return redirect('../myapp/myorders')
                 else:
                    request.session['last_login']=lastlogin
                    request.session.set_expiry(3600)
                    print(lastlogin)
                    return redirect('../myapp/myorders')
             else:
                return HttpResponse('Your account is disabled.')
         else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')

def user_logout(request):
    if request.session.has_key('username'):
        del request.session['username']
        logout(request)

        #now = datetime.datetime.now()
        #lastlogin = now.strftime("%m/%d/%Y, %H:%M:%S")
        request.session['last_login'] = lastlogin
        return HttpResponseRedirect('../myapp/login')
    else:
        return HttpResponseRedirect('../myapp/login')

def myorders(request):
    if request.session.has_key('username'):
        username = request.session['username']
        myorderlist = Order.objects.filter(client__first_name=username)

        return render(request, 'myapp/myorders.html', {'myorderlist': myorderlist})

    else:
        return HttpResponseRedirect('../myapp/login')
        #This else part will display if the user hasn't placed any order
def register(request):
    return render(request,"myapp/register.html")

def user_register(request):
    if request.POST:
        data = request.POST.copy()
        firstname = data.get('firstname')
        lastname = data.get('lastname')
        username = data.get('username')
        password = data.get('password')
        confirmpassword = data.get('confirmpassword')
        shippingaddress = data.get('address')
        city = data.get('city')
        province = data.get('province')
        interestedin = data.getlist('checks[]')

        if firstname.replace(" ", "").isalpha() and lastname.replace(" ", "").isalpha():
            if password == confirmpassword:
                client = Client.objects.create(first_name=firstname, last_name=lastname, username=username, shipping_address=shippingaddress,
                    city=city, province=province)
                client.set_password(password)
                client.interested_in.set(interestedin)
                client.save()
                messages.success(request, 'Registered successfully')
                return redirect('../myapp/login')
            else:
                messages.error(request, 'Password and Confirm-password must be same')
                return redirect('../myapp/register')
        else:
            messages.error(request, 'First name and Last name must be not empty')
            return redirect('../myapp/register')
    else:
        return redirect('../myapp/register')

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}About{% endblock %}
{% block body_block %}
    <body>
<h2>This is an Online Store APP</h2>
<p>
    <!-- <a href="./">Main page</a> -->
</p>
    <h4>Page visited: {{about_visits}}</h4>
</body>
{% endblock %}

myapp/templates/myapp/about0.html
<html>
<head lang="en"> <meta charset="UTF-8">
    <title>About Page</title>
<body>
<h2>This is an Online Store APP</h2>
<p>
    <a href="./">Main page</a>
</p>
</body>
</head>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
 <link rel="stylesheet" type="text/css" href="{% static 'myapp/styles.css' %}" />
 <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">

    <div class="navbar-nav ml-auto">
            {% block links %}
                {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link" href="./about">About</a>
                    <a class="nav-item nav-link" href = "{% url 'myapp:index' %}">Main page</a>
                    <a class="nav-item nav-link" href = "{% url 'myapp:products' %}">Products</a>
                    <a class="nav-item nav-link" href = "myorders">My orders</a>
                    <a class="nav-item nav-link" href = "logout">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="./about">About</a>
                    <a class="nav-item nav-link" href = "{% url 'myapp:index' %}">Main page</a>
                    <a class="nav-item nav-link" href = "{% url 'myapp:products' %}">Products</a>
                    <a class="nav-item nav-link" href = "../myapp/register">Register</a>
                    <a class="nav-item nav-link" href = "{% url 'myapp:login' %}">Login</a>
                {% endif %}
            {% endblock %}

    </div>
   </div>
</nav>
<h1> {% block myhdg %}
        Hello
        {% if request.user.is_authenticated %}
            {{user.first_name}}
        {% else %}
            User
        {% endif %}
      {% endblock %}
 </h1>
     {% block body_block %}*** {% endblock %}
<hr />
</body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}Detail{% endblock %}
{% block body_block %}
    <body>
{% if cat_list %}
    {% for cat in cat_list %}
        <h2>Name: {{ cat.name }}</h2>
        <h2>Warehouse: {{ cat.warehouse }}</h2>
    {% endfor %}
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
{% if product_list %}
    <ol>
    {% for p in product_list %}
        <li>{{ p.name }}</li>
    {% endfor %}
    </ol>
{% else %}
    <strong>There are no available products!</strong>
{% endif %}
<p>
    <!-- <a href="./">Main page</a> -->
</p>
</body>
{% endblock %}

myapp/templates/myapp/detail0.html
<html>
<head lang="en"> <meta charset="UTF-8">
    <title>Detail Page</title>
<body>
{% if cat_list %}
    {% for cat in cat_list %}
        <h2>Name: {{ cat.name }}</h2>
        <h2>Warehouse: {{ cat.warehouse }}</h2>
    {% endfor %}
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
{% if product_list %}
    <ol>
    {% for p in product_list %}
        <li>{{ p.name }}</li>
    {% endfor %}
    </ol>
{% else %}
    <strong>There are no available products!</strong>
{% endif %}
<p>
   <!-- <a href="{% url 'myapp:index' %}">Main page</a> -->
</p>
</body>
</head>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <body>
{% if cat_list %}
    <h2>List of Categories</h2>
    <ol> {% for cat in cat_list %}
        <li><a href="/myapp/{{ cat.id}}">{{ cat.name}}</a>  </li>
    {% endfor %}
    </ol>
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
{% if last_login != '' %}
<h4>Last Login: {{last_login}}</h4>
{% endif %}
</body>
{% endblock %}

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en"> <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>
{% if cat_list %}
    <h2>List of Categories</h2>
    <ol> {% for cat in cat_list %}
        <li><a href="/{{ cat.id}}">{{ cat.name}}</a>  </li>
    {% endfor %}
    </ol>
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
<p>
    <a href="{% url 'myapp:about' %}">About page</a>
</p>
</body>
</html>

myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block body_block %}
{% load crispy_forms_tags %}
<html>
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
{% if messages %}
    {% for message in messages %}
        <div>
            <strong>Message:{{message}}</strong>
        </div>
    {% endfor %}
{% endif %}
<div class="jumbotron">
    <div class="container">
<h1>Login</h1>
<form action="user_login" method="post">
{% csrf_token %}
    {{ form|crispy }}
Username:&nbsp;&nbsp;<input type="text" name="username" id="username" required/><br><br>
Password:&nbsp;&nbsp;<input type="password" name="password" id="password" required/><br><br>
<button type="submit" class="btn btn-success"> Login</button>
</form>
        <p> <a href="{% url 'password_reset' %}">Forget your Password</a></p>
        <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
    </div>
    </div>
</body>
{% endblock %}

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<body>
{% if myorderlist %}
<h1>List of Products</h1>
{% for m in myorderlist %}
<ol>
{{ m.product}}
</ol>
{% endfor %}
{% else %}
<strong>There are no orders by you!</strong>
{% endif %}
</body>
{% endblock %}

myapp/templates/myapp/orderresponse.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<body>
 <h1>Message: {{msg}} </h1>  <!--Displays not sufficient stocks available message-->
</body>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<body>
 {% if prodlist %}
 <h1>List of Products</h1>
 <ol>
 {% for p in prodlist %}
     <li> <p>{{ p.name }} - {{p.price}} </p></li>
 {% endfor %}
 </ol>
 {% else %}
 <strong>There are no available products!</strong>
 {% endif %}

 <h1>Place Order:</h1>   <!--Places the order from the form created -->
 <form action="../myapp/placeorder" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

     <p><a href="about">About page</a></p>
</body>
{% endblock %}

myapp/templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<body>
 {% if proddetail %} <!--Displays the details about the product and the number of people Interested-->
 <h1>Product Detail</h1>
 <h3>Name: {{proddetail.name}} </h3>
 <h3>People Interested: {{proddetail.interested}} </h3>
 <h3>Price: {{proddetail.price}} </h3>
 {% if proddetail.stock <= 0  %}
 <h3>Message: Product Not available</h3>
 {% endif %}
 {% endif %}
 <form action="../products/{{proddetail.id}}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
 </form>
     <!-- <p><a href="about">About page</a></p> -->
</body>
{% endblock %}

myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}
{% block body_block %}
<body>
 {% if prodlist %}
 <h1>List of Products</h1>
 <ol>
 {% for p in prodlist %} <!--Lists the Products and if not available then it displays necessary message-->
  <li><a href="/myapp/products/{{ p.id }}"> {{ p.name}} </a> </li>
 {% endfor %}
 </ol>
 {% else %}
 <strong>There are no available Products!</strong>
 {% endif %}
    <p><a href="placeorder">Place Order</a></p>
     <p><a href="about">About page</a></p>
</body>
{% endblock %}

myapp/templates/myapp/register.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    {% if messages %}
                {% for message in messages %}
                    <div>
                        <strong>Message:{{message}}</strong>
                    </div>
                {% endfor %}
            {% endif %}
    <div class="jumbotron">
    <div class="container">
    <h1>Register</h1>
    <form action="user_register" method="post">
        {% csrf_token %}
        <div class="form-row">
        <div class="form-group col-md-6">
        First Name:&nbsp;&nbsp;<input type="text" name="firstname" id="firstname" required/></div>
        <div class="form-group col-md-6">Last Name:&nbsp;&nbsp;<input type="text" name="lastname" id="lastname" required/></div> </div>
        <div class="form-row">
        Username:&nbsp;&nbsp;&nbsp;&nbsp<input type="text" name="username" id="username" required/></div>
        <div class="form-row">
        <div class="form-group col-md-6">
         Password:&nbsp;&nbsp;&nbsp;&nbsp;<input type="password" name="password" id="password" required/> </div>
            <div class="form-group col-md-6">
            Confirm Password:&nbsp;&nbsp;<input type="password" name="confirmpassword" id="confirmpassword" required/></div> </div>
        Address: &nbsp;&nbsp;&nbsp;&nbsp;
        <input type="text" name="address" id="address" required/><br><br>
        City: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="city" id="city" required/><br><br>
        Province:<br>
        <input type="radio" name="province" value="Alberta"> Alberta<br>
        <input type="radio" name="province" value="Manitoba"> Manitoba<br>
        <input type="radio" name="province" value="Ontario"> Ontario<br>
        <input type="radio" name="province" value="Quebec"> Quebec<br><br>
        Interested in:<br>
        <input type="checkbox" name="checks[]" value="1"> Furniture<br>
        <input type="checkbox" name="checks[]" value="2"> Appliances<br>
        <input type="checkbox" name="checks[]" value="3"> Electronics<br>
        <input type="checkbox" name="checks[]" value="4"> Home Decor<br>
        <input type="checkbox" name="checks[]" value="5"> Flooring<br><br>
        <button type="submit" class="btn btn-success"> Register</button>
    </form>
    </div>
    </div>
</body>
</html>